version: '3'
services: 
  app:
    container_name: Node-Express-API
    restart: always
    environment:
      - PORT=5000
      - URL=http://localhost
      - MONGO_URL=mongodb://mongo:27017
      - DB_NAME=socialDBMS
    build: .
    volumes:
      - .:/app
    ports:
      - '5000:5000'
    depends_on:
      - mongo
  mongo:
    container_name: mongodb-socialDBMS
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - data:/data/db
volumes:
  data:

     
#DATABASE_CONNECTION_URL=mongodb://mongo:27017/socialDBMS

#container_name: social-network-API
#container_name: mongodb-socialDBMS
# links:
      #- mongodb
#docker-compose up
#docker-compose down OR control C
#docker-compose build
#docker start CONTAINER_NAME
#docker run --name NAME_OF_DATABASE_CONTAINER -d -p 27017:27017 mongo


#   mongo:
#     image: mongo
#     restart: always
#     container_name: mongo-docker
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: 
#       MONGO_INITDB_ROOT_PASSWORD: 
#       #MONGODB_AUTH_DATABASE: admin
#     ports:
#       - "27017:27017"
#     volumes:
#       - ./workspace:/workspace
#       - type: volume
#         source: mongodb_data_volume
#         target: /data/db
        
#   mongo-express:
#     image: mongo-express
#     container_name: mongo-express
#     restart: always
#     ports:
#       - '8080:5000'
#     environment:
#       ME_CONFIG_MONGODB_SERVER: mongo
#       ME_CONFIG_BASICAUTH_USERNAME: 
#       ME_CONFIG_BASICAUTH_PASSWORD: 
#       #ME_CONFIG_MONGODB_AUTH_DATABASE: admin
#       ME_CONFIG_MONGODB_ADMINUSERNAME: 
#       ME_CONFIG_MONGODB_ADMINPASSWORD: 
#       ME_CONFIG_MONGODB_URL: mongo://mongo:27017/socialDBMS
#     depends_on:
#       - mongo

# volumes:
#   mongodb_data_volume:
#     driver: local 